bump forge, add debug

diff --git a/.github/workflows/release-test-version.yml b/.github/workflows/release-test-version.yml
--- a/.github/workflows/release-test-version.yml
+++ b/.github/workflows/release-test-version.yml
@@ -22,7 +22,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        platform: [macos-latest, macos-15-intel, windows-latest, ubuntu-latest]
+        platform: [macos-15-intel]
 
     runs-on: ${{ matrix.platform }}
     steps:
@@ -72,24 +72,25 @@ jobs:
           security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
           security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$CERTIFICATE_PASSWORD" build.keychain
 
-      - name: publish macOS arm64
-        if: startsWith(matrix.platform, 'macos-latest')
-        env:
-          NODE_OPTIONS: '--max_old_space_size=8192'
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # apple notarization
-          APPLE_API_KEY: ./apple_api_key.p8
-          # sentry integration
-          # sentry vite plugin integration during build
-          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
-        run: |
-          npm run publish
+      # - name: publish macOS arm64
+        # if: startsWith(matrix.platform, 'macos-latest')
+        # env:
+          # NODE_OPTIONS: '--max_old_space_size=8192'
+          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # # apple notarization
+          # APPLE_API_KEY: ./apple_api_key.p8
+          # # sentry integration
+          # # sentry vite plugin integration during build
+          # SENTRY_ORG: ${{ vars.SENTRY_ORG }}
+          # SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
+        # run: |
+          # npm run publish
 
       - name: publish macOS x86_64
         if: startsWith(matrix.platform, 'macos-15-intel')
         env:
           NODE_OPTIONS: '--max_old_space_size=8192'
+          DEBUG: 'electron-rebuild*,electron-forge*'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           # apple notarization
           APPLE_API_KEY: ./apple_api_key.p8
@@ -100,86 +101,86 @@ jobs:
         run: |
           npm run publish -- --arch=x64
 
-      - name: Get azure secrets
-        id: get-azure-secrets
-        uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b # v1.2.0
-        if: startsWith(matrix.platform, 'windows-')
-        with:
-          export_env: false
-          repo_secrets: |
-            client-id=azure-trusted-signing:client-id
-            subscription-id=azure-trusted-signing:subscription-id
-            tenant-id=azure-trusted-signing:tenant-id
+      # - name: Get azure secrets
+        # id: get-azure-secrets
+        # uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b # v1.2.0
+        # if: startsWith(matrix.platform, 'windows-')
+        # with:
+          # export_env: false
+          # repo_secrets: |
+            # client-id=azure-trusted-signing:client-id
+            # subscription-id=azure-trusted-signing:subscription-id
+            # tenant-id=azure-trusted-signing:tenant-id
 
-      - name: Azure log in
-        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
-        if: startsWith(matrix.platform, 'windows-')
-        with:
-          client-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).client-id }}
-          subscription-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).subscription-id }}
-          tenant-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).tenant-id }}
+      # - name: Azure log in
+        # uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
+        # if: startsWith(matrix.platform, 'windows-')
+        # with:
+          # client-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).client-id }}
+          # subscription-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).subscription-id }}
+          # tenant-id: ${{ fromJSON(steps.get-azure-secrets.outputs.secrets).tenant-id }}
 
-      - name: Setup .NET SDK
-        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
-        if: startsWith(matrix.platform, 'windows-')
-        with:
-          # renovate: datasource=dotnet-version depName=dotnet-sdk
-          dotnet-version: "8.0.414"
+      # - name: Setup .NET SDK
+        # uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
+        # if: startsWith(matrix.platform, 'windows-')
+        # with:
+          # # renovate: datasource=dotnet-version depName=dotnet-sdk
+          # dotnet-version: "8.0.414"
 
-      - name: Install Sign CLI tool
-        id: install-sign-tool
-        if: startsWith(matrix.platform, 'windows-')
-        shell: pwsh
-        env:
-          # renovate: datasource=nuget depName=sign
-          DOTNET_SIGN_VERSION: "0.9.1-beta.25379.1"
-        run: |
-          $toolPath = Join-Path -Path ${env:RUNNER_TEMP} -ChildPath (New-Guid).ToString()
-          New-Item -ItemType Directory -Path $toolPath | Out-Null
+      # - name: Install Sign CLI tool
+        # id: install-sign-tool
+        # if: startsWith(matrix.platform, 'windows-')
+        # shell: pwsh
+        # env:
+          # # renovate: datasource=nuget depName=sign
+          # DOTNET_SIGN_VERSION: "0.9.1-beta.25379.1"
+        # run: |
+          # $toolPath = Join-Path -Path ${env:RUNNER_TEMP} -ChildPath (New-Guid).ToString()
+          # New-Item -ItemType Directory -Path $toolPath | Out-Null
 
-          dotnet tool install --tool-path $toolPath sign --version ${env:DOTNET_SIGN_VERSION}
+          # dotnet tool install --tool-path $toolPath sign --version ${env:DOTNET_SIGN_VERSION}
 
-          if ($LASTEXITCODE -ne 0) {
-            Write-Output "::error::Failed to install Sign CLI tool"
-            exit 1
-          }
+          # if ($LASTEXITCODE -ne 0) {
+            # Write-Output "::error::Failed to install Sign CLI tool"
+            # exit 1
+          # }
 
-          "sign-tool=$toolPath" >> ${env:GITHUB_OUTPUT}
+          # "sign-tool=$toolPath" >> ${env:GITHUB_OUTPUT}
 
-      - name: publish Windows
-        if: startsWith(matrix.platform, 'windows-')
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # windows cert
-          TRUSTED_SIGNING_ACCOUNT: grafana-premium-eastus
-          TRUSTED_SIGNING_ENDPOINT: https://eus.codesigning.azure.net/
-          TRUSTED_SIGNING_PROFILE: grafana-production
-          SIGNTOOL_PATH: ${{ steps.install-sign-tool.outputs.sign-tool }}\sign
-          # sentry integration
-          # sentry vite plugin integration during build
-          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
-        run: npm run publish
+      # - name: publish Windows
+        # if: startsWith(matrix.platform, 'windows-')
+        # env:
+          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # # windows cert
+          # TRUSTED_SIGNING_ACCOUNT: grafana-premium-eastus
+          # TRUSTED_SIGNING_ENDPOINT: https://eus.codesigning.azure.net/
+          # TRUSTED_SIGNING_PROFILE: grafana-production
+          # SIGNTOOL_PATH: ${{ steps.install-sign-tool.outputs.sign-tool }}\sign
+          # # sentry integration
+          # # sentry vite plugin integration during build
+          # SENTRY_ORG: ${{ vars.SENTRY_ORG }}
+          # SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
+        # run: npm run publish
 
-      - name: publish Linux
-        if: startsWith(matrix.platform, 'ubuntu-')
-        env:
-          NODE_OPTIONS: '--max_old_space_size=8192'
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # sentry integration
-          # sentry vite plugin integration during build
-          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
-          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
-        run: |
-          sudo apt install -y rpm
+      # - name: publish Linux
+        # if: startsWith(matrix.platform, 'ubuntu-')
+        # env:
+          # NODE_OPTIONS: '--max_old_space_size=8192'
+          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # # sentry integration
+          # # sentry vite plugin integration during build
+          # SENTRY_ORG: ${{ vars.SENTRY_ORG }}
+          # SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
+        # run: |
+          # sudo apt install -y rpm
 
-          # There is a bug on Ubuntu 22.04 (ubuntu-latest) regarding stripping a binary for a different architecture.
-          # https://github.com/electron/forge/issues/3102
-          # https://github.com/electron/forge/issues/3701
-          echo "%__strip /bin/true" >> ~/.rpmmacros
+          # # There is a bug on Ubuntu 22.04 (ubuntu-latest) regarding stripping a binary for a different architecture.
+          # # https://github.com/electron/forge/issues/3102
+          # # https://github.com/electron/forge/issues/3701
+          # echo "%__strip /bin/true" >> ~/.rpmmacros
 
-          npm run publish
-          npm run publish -- --arch=arm64
+          # npm run publish
+          # npm run publish -- --arch=arm64
 
       - name: cleanup macos certificates
         if: startsWith(matrix.platform, 'macos-')
